// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meetingService.proto

package com.example.demo.serviceImpl.meetingService;

public final class MeetingService {
  private MeetingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeetingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.demo.serviceImpl.meetingService.Meeting)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <code>string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.demo.serviceImpl.meetingService.Meeting}
   */
  public  static final class Meeting extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.demo.serviceImpl.meetingService.Meeting)
      MeetingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meeting.newBuilder() to construct.
    private Meeting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meeting() {
      id_ = 0;
      userId_ = 0;
      userName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meeting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (time_ != null) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Meeting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.class, com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp time_;
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return getTime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (time_ != null) {
        output.writeMessage(4, getTime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.serviceImpl.meetingService.MeetingService.Meeting)) {
        return super.equals(obj);
      }
      com.example.demo.serviceImpl.meetingService.MeetingService.Meeting other = (com.example.demo.serviceImpl.meetingService.MeetingService.Meeting) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && getTime()
            .equals(other.getTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.serviceImpl.meetingService.MeetingService.Meeting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.demo.serviceImpl.meetingService.Meeting}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.demo.serviceImpl.meetingService.Meeting)
        com.example.demo.serviceImpl.meetingService.MeetingService.MeetingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Meeting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.class, com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.Builder.class);
      }

      // Construct using com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        userId_ = 0;

        userName_ = "";

        if (timeBuilder_ == null) {
          time_ = null;
        } else {
          time_ = null;
          timeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor;
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Meeting getDefaultInstanceForType() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Meeting build() {
        com.example.demo.serviceImpl.meetingService.MeetingService.Meeting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Meeting buildPartial() {
        com.example.demo.serviceImpl.meetingService.MeetingService.Meeting result = new com.example.demo.serviceImpl.meetingService.MeetingService.Meeting(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.userName_ = userName_;
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.serviceImpl.meetingService.MeetingService.Meeting) {
          return mergeFrom((com.example.demo.serviceImpl.meetingService.MeetingService.Meeting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.serviceImpl.meetingService.MeetingService.Meeting other) {
        if (other == com.example.demo.serviceImpl.meetingService.MeetingService.Meeting.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.demo.serviceImpl.meetingService.MeetingService.Meeting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.demo.serviceImpl.meetingService.MeetingService.Meeting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp time_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public boolean hasTime() {
        return timeBuilder_ != null || time_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (time_ != null) {
            time_ =
              com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = null;
          onChanged();
        } else {
          time_ = null;
          timeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.demo.serviceImpl.meetingService.Meeting)
    }

    // @@protoc_insertion_point(class_scope:com.example.demo.serviceImpl.meetingService.Meeting)
    private static final com.example.demo.serviceImpl.meetingService.MeetingService.Meeting DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.serviceImpl.meetingService.MeetingService.Meeting();
    }

    public static com.example.demo.serviceImpl.meetingService.MeetingService.Meeting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meeting>
        PARSER = new com.google.protobuf.AbstractParser<Meeting>() {
      @java.lang.Override
      public Meeting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meeting(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meeting> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Meeting> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.serviceImpl.meetingService.MeetingService.Meeting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.demo.serviceImpl.meetingService.Report)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 numOfMeetings = 1;</code>
     */
    int getNumOfMeetings();

    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */
    int getStatByDayOfTheWeekCount();
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */
    boolean containsStatByDayOfTheWeek(
        int key);
    /**
     * Use {@link #getStatByDayOfTheWeekMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Double>
    getStatByDayOfTheWeek();
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Double>
    getStatByDayOfTheWeekMap();
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    double getStatByDayOfTheWeekOrDefault(
        int key,
        double defaultValue);
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    double getStatByDayOfTheWeekOrThrow(
        int key);

    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */
    int getStatByUserCount();
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */
    boolean containsStatByUser(
        int key);
    /**
     * Use {@link #getStatByUserMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Double>
    getStatByUser();
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Double>
    getStatByUserMap();
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    double getStatByUserOrDefault(
        int key,
        double defaultValue);
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    double getStatByUserOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code com.example.demo.serviceImpl.meetingService.Report}
   */
  public  static final class Report extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.demo.serviceImpl.meetingService.Report)
      ReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Report.newBuilder() to construct.
    private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Report() {
      numOfMeetings_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Report(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numOfMeetings_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                statByDayOfTheWeek_ = com.google.protobuf.MapField.newMapField(
                    StatByDayOfTheWeekDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
              statByDayOfTheWeek__ = input.readMessage(
                  StatByDayOfTheWeekDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              statByDayOfTheWeek_.getMutableMap().put(
                  statByDayOfTheWeek__.getKey(), statByDayOfTheWeek__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                statByUser_ = com.google.protobuf.MapField.newMapField(
                    StatByUserDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
              statByUser__ = input.readMessage(
                  StatByUserDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              statByUser_.getMutableMap().put(
                  statByUser__.getKey(), statByUser__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetStatByDayOfTheWeek();
        case 3:
          return internalGetStatByUser();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.serviceImpl.meetingService.MeetingService.Report.class, com.example.demo.serviceImpl.meetingService.MeetingService.Report.Builder.class);
    }

    private int bitField0_;
    public static final int NUMOFMEETINGS_FIELD_NUMBER = 1;
    private int numOfMeetings_;
    /**
     * <code>int32 numOfMeetings = 1;</code>
     */
    public int getNumOfMeetings() {
      return numOfMeetings_;
    }

    public static final int STATBYDAYOFTHEWEEK_FIELD_NUMBER = 2;
    private static final class StatByDayOfTheWeekDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Double>newDefaultInstance(
                  com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Double> statByDayOfTheWeek_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
    internalGetStatByDayOfTheWeek() {
      if (statByDayOfTheWeek_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatByDayOfTheWeekDefaultEntryHolder.defaultEntry);
      }
      return statByDayOfTheWeek_;
    }

    public int getStatByDayOfTheWeekCount() {
      return internalGetStatByDayOfTheWeek().getMap().size();
    }
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    public boolean containsStatByDayOfTheWeek(
        int key) {
      
      return internalGetStatByDayOfTheWeek().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatByDayOfTheWeekMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Double> getStatByDayOfTheWeek() {
      return getStatByDayOfTheWeekMap();
    }
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Double> getStatByDayOfTheWeekMap() {
      return internalGetStatByDayOfTheWeek().getMap();
    }
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    public double getStatByDayOfTheWeekOrDefault(
        int key,
        double defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Double> map =
          internalGetStatByDayOfTheWeek().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
     */

    public double getStatByDayOfTheWeekOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Double> map =
          internalGetStatByDayOfTheWeek().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int STATBYUSER_FIELD_NUMBER = 3;
    private static final class StatByUserDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Double>newDefaultInstance(
                  com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Double> statByUser_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
    internalGetStatByUser() {
      if (statByUser_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatByUserDefaultEntryHolder.defaultEntry);
      }
      return statByUser_;
    }

    public int getStatByUserCount() {
      return internalGetStatByUser().getMap().size();
    }
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    public boolean containsStatByUser(
        int key) {
      
      return internalGetStatByUser().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatByUserMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Double> getStatByUser() {
      return getStatByUserMap();
    }
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Double> getStatByUserMap() {
      return internalGetStatByUser().getMap();
    }
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    public double getStatByUserOrDefault(
        int key,
        double defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Double> map =
          internalGetStatByUser().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, double&gt; statByUser = 3;</code>
     */

    public double getStatByUserOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Double> map =
          internalGetStatByUser().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numOfMeetings_ != 0) {
        output.writeInt32(1, numOfMeetings_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetStatByDayOfTheWeek(),
          StatByDayOfTheWeekDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetStatByUser(),
          StatByUserDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numOfMeetings_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numOfMeetings_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetStatByDayOfTheWeek().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        statByDayOfTheWeek__ = StatByDayOfTheWeekDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, statByDayOfTheWeek__);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Double> entry
           : internalGetStatByUser().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Double>
        statByUser__ = StatByUserDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, statByUser__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.demo.serviceImpl.meetingService.MeetingService.Report)) {
        return super.equals(obj);
      }
      com.example.demo.serviceImpl.meetingService.MeetingService.Report other = (com.example.demo.serviceImpl.meetingService.MeetingService.Report) obj;

      boolean result = true;
      result = result && (getNumOfMeetings()
          == other.getNumOfMeetings());
      result = result && internalGetStatByDayOfTheWeek().equals(
          other.internalGetStatByDayOfTheWeek());
      result = result && internalGetStatByUser().equals(
          other.internalGetStatByUser());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMOFMEETINGS_FIELD_NUMBER;
      hash = (53 * hash) + getNumOfMeetings();
      if (!internalGetStatByDayOfTheWeek().getMap().isEmpty()) {
        hash = (37 * hash) + STATBYDAYOFTHEWEEK_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStatByDayOfTheWeek().hashCode();
      }
      if (!internalGetStatByUser().getMap().isEmpty()) {
        hash = (37 * hash) + STATBYUSER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStatByUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.demo.serviceImpl.meetingService.MeetingService.Report prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.demo.serviceImpl.meetingService.Report}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.demo.serviceImpl.meetingService.Report)
        com.example.demo.serviceImpl.meetingService.MeetingService.ReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetStatByDayOfTheWeek();
          case 3:
            return internalGetStatByUser();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableStatByDayOfTheWeek();
          case 3:
            return internalGetMutableStatByUser();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.demo.serviceImpl.meetingService.MeetingService.Report.class, com.example.demo.serviceImpl.meetingService.MeetingService.Report.Builder.class);
      }

      // Construct using com.example.demo.serviceImpl.meetingService.MeetingService.Report.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numOfMeetings_ = 0;

        internalGetMutableStatByDayOfTheWeek().clear();
        internalGetMutableStatByUser().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor;
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Report getDefaultInstanceForType() {
        return com.example.demo.serviceImpl.meetingService.MeetingService.Report.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Report build() {
        com.example.demo.serviceImpl.meetingService.MeetingService.Report result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.demo.serviceImpl.meetingService.MeetingService.Report buildPartial() {
        com.example.demo.serviceImpl.meetingService.MeetingService.Report result = new com.example.demo.serviceImpl.meetingService.MeetingService.Report(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.numOfMeetings_ = numOfMeetings_;
        result.statByDayOfTheWeek_ = internalGetStatByDayOfTheWeek();
        result.statByDayOfTheWeek_.makeImmutable();
        result.statByUser_ = internalGetStatByUser();
        result.statByUser_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.demo.serviceImpl.meetingService.MeetingService.Report) {
          return mergeFrom((com.example.demo.serviceImpl.meetingService.MeetingService.Report)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.demo.serviceImpl.meetingService.MeetingService.Report other) {
        if (other == com.example.demo.serviceImpl.meetingService.MeetingService.Report.getDefaultInstance()) return this;
        if (other.getNumOfMeetings() != 0) {
          setNumOfMeetings(other.getNumOfMeetings());
        }
        internalGetMutableStatByDayOfTheWeek().mergeFrom(
            other.internalGetStatByDayOfTheWeek());
        internalGetMutableStatByUser().mergeFrom(
            other.internalGetStatByUser());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.demo.serviceImpl.meetingService.MeetingService.Report parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.demo.serviceImpl.meetingService.MeetingService.Report) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int numOfMeetings_ ;
      /**
       * <code>int32 numOfMeetings = 1;</code>
       */
      public int getNumOfMeetings() {
        return numOfMeetings_;
      }
      /**
       * <code>int32 numOfMeetings = 1;</code>
       */
      public Builder setNumOfMeetings(int value) {
        
        numOfMeetings_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numOfMeetings = 1;</code>
       */
      public Builder clearNumOfMeetings() {
        
        numOfMeetings_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Double> statByDayOfTheWeek_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetStatByDayOfTheWeek() {
        if (statByDayOfTheWeek_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StatByDayOfTheWeekDefaultEntryHolder.defaultEntry);
        }
        return statByDayOfTheWeek_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetMutableStatByDayOfTheWeek() {
        onChanged();;
        if (statByDayOfTheWeek_ == null) {
          statByDayOfTheWeek_ = com.google.protobuf.MapField.newMapField(
              StatByDayOfTheWeekDefaultEntryHolder.defaultEntry);
        }
        if (!statByDayOfTheWeek_.isMutable()) {
          statByDayOfTheWeek_ = statByDayOfTheWeek_.copy();
        }
        return statByDayOfTheWeek_;
      }

      public int getStatByDayOfTheWeekCount() {
        return internalGetStatByDayOfTheWeek().getMap().size();
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public boolean containsStatByDayOfTheWeek(
          int key) {
        
        return internalGetStatByDayOfTheWeek().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStatByDayOfTheWeekMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Double> getStatByDayOfTheWeek() {
        return getStatByDayOfTheWeekMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Double> getStatByDayOfTheWeekMap() {
        return internalGetStatByDayOfTheWeek().getMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public double getStatByDayOfTheWeekOrDefault(
          int key,
          double defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Double> map =
            internalGetStatByDayOfTheWeek().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public double getStatByDayOfTheWeekOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Double> map =
            internalGetStatByDayOfTheWeek().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStatByDayOfTheWeek() {
        internalGetMutableStatByDayOfTheWeek().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public Builder removeStatByDayOfTheWeek(
          int key) {
        
        internalGetMutableStatByDayOfTheWeek().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Double>
      getMutableStatByDayOfTheWeek() {
        return internalGetMutableStatByDayOfTheWeek().getMutableMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */
      public Builder putStatByDayOfTheWeek(
          int key,
          double value) {
        
        
        internalGetMutableStatByDayOfTheWeek().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, double&gt; statByDayOfTheWeek = 2;</code>
       */

      public Builder putAllStatByDayOfTheWeek(
          java.util.Map<java.lang.Integer, java.lang.Double> values) {
        internalGetMutableStatByDayOfTheWeek().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Double> statByUser_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetStatByUser() {
        if (statByUser_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StatByUserDefaultEntryHolder.defaultEntry);
        }
        return statByUser_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Double>
      internalGetMutableStatByUser() {
        onChanged();;
        if (statByUser_ == null) {
          statByUser_ = com.google.protobuf.MapField.newMapField(
              StatByUserDefaultEntryHolder.defaultEntry);
        }
        if (!statByUser_.isMutable()) {
          statByUser_ = statByUser_.copy();
        }
        return statByUser_;
      }

      public int getStatByUserCount() {
        return internalGetStatByUser().getMap().size();
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public boolean containsStatByUser(
          int key) {
        
        return internalGetStatByUser().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStatByUserMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Double> getStatByUser() {
        return getStatByUserMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Double> getStatByUserMap() {
        return internalGetStatByUser().getMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public double getStatByUserOrDefault(
          int key,
          double defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Double> map =
            internalGetStatByUser().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public double getStatByUserOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Double> map =
            internalGetStatByUser().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStatByUser() {
        internalGetMutableStatByUser().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public Builder removeStatByUser(
          int key) {
        
        internalGetMutableStatByUser().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Double>
      getMutableStatByUser() {
        return internalGetMutableStatByUser().getMutableMap();
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */
      public Builder putStatByUser(
          int key,
          double value) {
        
        
        internalGetMutableStatByUser().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, double&gt; statByUser = 3;</code>
       */

      public Builder putAllStatByUser(
          java.util.Map<java.lang.Integer, java.lang.Double> values) {
        internalGetMutableStatByUser().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.demo.serviceImpl.meetingService.Report)
    }

    // @@protoc_insertion_point(class_scope:com.example.demo.serviceImpl.meetingService.Report)
    private static final com.example.demo.serviceImpl.meetingService.MeetingService.Report DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.demo.serviceImpl.meetingService.MeetingService.Report();
    }

    public static com.example.demo.serviceImpl.meetingService.MeetingService.Report getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Report>
        PARSER = new com.google.protobuf.AbstractParser<Report>() {
      @java.lang.Override
      public Report parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Report(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Report> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Report> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.demo.serviceImpl.meetingService.MeetingService.Report getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_serviceImpl_meetingService_Meeting_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_serviceImpl_meetingService_Report_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024meetingService.proto\022+com.example.demo" +
      ".serviceImpl.meetingService\032\036google/prot" +
      "obuf/wrappers.proto\032\037google/protobuf/tim" +
      "estamp.proto\"a\n\007Meeting\022\n\n\002id\030\001 \001(\005\022\016\n\006u" +
      "serId\030\002 \001(\005\022\020\n\010userName\030\003 \001(\t\022(\n\004time\030\004 " +
      "\001(\0132\032.google.protobuf.Timestamp\"\317\002\n\006Repo" +
      "rt\022\025\n\rnumOfMeetings\030\001 \001(\005\022g\n\022statByDayOf" +
      "TheWeek\030\002 \003(\0132K.com.example.demo.service" +
      "Impl.meetingService.Report.StatByDayOfTh" +
      "eWeekEntry\022W\n\nstatByUser\030\003 \003(\0132C.com.exa" +
      "mple.demo.serviceImpl.meetingService.Rep" +
      "ort.StatByUserEntry\0329\n\027StatByDayOfTheWee" +
      "kEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\001:\0028\001\0321" +
      "\n\017StatByUserEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030" +
      "\002 \001(\001:\0028\0012\272\002\n\016MeetingManager\022_\n\naddMeeti" +
      "ng\0224.com.example.demo.serviceImpl.meetin" +
      "gService.Meeting\032\033.google.protobuf.Int32" +
      "Value\022f\n\017getUserMeetings\022\033.google.protob" +
      "uf.Int32Value\0324.com.example.demo.service" +
      "Impl.meetingService.Meeting0\001\022_\n\tgetRepo" +
      "rt\022\033.google.protobuf.Int32Value\0323.com.ex" +
      "ample.demo.serviceImpl.meetingService.Re" +
      "port(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_serviceImpl_meetingService_Meeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_serviceImpl_meetingService_Meeting_descriptor,
        new java.lang.String[] { "Id", "UserId", "UserName", "Time", });
    internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_serviceImpl_meetingService_Report_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor,
        new java.lang.String[] { "NumOfMeetings", "StatByDayOfTheWeek", "StatByUser", });
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_descriptor =
      internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor.getNestedTypes().get(0);
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByDayOfTheWeekEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_descriptor =
      internal_static_com_example_demo_serviceImpl_meetingService_Report_descriptor.getNestedTypes().get(1);
    internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_serviceImpl_meetingService_Report_StatByUserEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
